### ISSUE TITLE
Explorer l’outil de publication ontologie Widoco

### ISSUE THREAD

**Issue by emchateau** [ouvroir/display-ontology#4]
https://github.com/dgarijo/Widoco et https://essepuntato.it/lode/
ex. https://www.cfregisters.org/#!/outils/ressources/documentation

**Comment by davvalent** [comment]
Salut, je planifiais utiliser LODE, mais l'apport de Widoco semble très bien, j'y jette un œil.

**Comment by davvalent** [comment]
Voir aussi [pyLODE](https://github.com/RDFLib/pyLODE) (activement maintenu et fonctionnalités supplémentaires)

**Comment by emchateau** [comment]
Comme je suis un peu intégriste, mais je ne vois pas trop l’intérêt d’utiliser Python pour ce genre d’application... Mais je suis sans doute trop intégriste et les jeunes ne savent plus faire du XSLT

**Comment by emchateau** [comment]
Comme il ne s’agit pas de la source mais seulement du générateur de doc on peut se permettre

**Comment by davvalent** [comment]
Comme discuté, ce sera Widoco. Ça va faire le travail et nous aurons bientôt un dépôt en ligne pour gérer la documentation de l'ontologie.

**Comment by davvalent** [comment]
Je me permets de fermer ce billet. Widoco n'a plus vraiment de secrets pour nous.
